import React, { useEffect, useState } from 'react'
import AuctionCollapsible from 'src/components/AuctionCollapsible'
import Hero from 'src/components/Hero'
import Meta from 'src/components/Meta'

export default function Home() {
  
  const [openSection, setOpenSection] = useState('auctions');

  let propList = {
    meta: {
      title: 'DJ\'s Auction House',
      description: 'DJ\'s Auction House is selling everything you could possibly need or want! Get in quick to see our latest items!',
      image: {
        src: '/images/favicon.png',
        alt: 'DJ\'s Auction House',
        width: 1024,
        height: 1024,
      },
    },
    hero: {
      title: `DJ's Auction House`,
      backgroundImage: '/images/hero/hero.jpg',
    },
    AuctionSections: [
      {
        title: 'Auctions',
        auctions: [
          {
            "Lot Number": "0401",
            "Lot Title": "Jerry Rice Rookie RC Card / Commemorative Ticket/8x10 Autograph",
            "Lot Description": "Picture(s) part of description. 1986 TOPPS Rookie Card #161 / 1997 Jerry Rice's 1000 Receptions Commemorative Ticket #1403 out of 10000 / 8 x 10 Autograph Photo with COA",
            "Starting Bid": 100,
            "Quantity": 1,
            "Reserve": 150,
            "image": "/images/auctions/7/0401.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0401",
          },
          {
            "Lot Number": "0101",
            "Lot Title": "THE DOORS LASERDISC",
            "Lot Description": "Picture(s) part of description. Double disc set widescreen edition. Starring Val Kilmer & Meg Ryan",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0101.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0101",
          },
          {
            "Lot Number": "0402",
            "Lot Title": "TOPPS Stadium Club 50 Card Set",
            "Lot Description": "Picture(s) part of description. Members Only Football 1996",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0402.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0402",
          },
          {
            "Lot Number": "0403",
            "Lot Title": "PSA 8 x 10 Autograph Bernie Kozar",
            "Lot Description": "Picture(s) part of description. Certificate of Authenticity ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/7/0403.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0403",
          },
          {
            "Lot Number": "0102",
            "Lot Title": "LOT OF 3 BOB SEGER & THE SILVER BULLET BAND VINYL LP",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0102.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0102",
          },
          {
            "Lot Number": "0404",
            "Lot Title": "Dan Marino Lot of 2 ",
            "Lot Description": "Picture(s) part of description. (1) 1994 Collectors Edge 22K Excalibur 22 of 25 / (2) PD-25 Power Deck by Upper Deck",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0404.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0404",
          },
          {
            "Lot Number": "0405",
            "Lot Title": "Deion Sanders 1993 Game Day Collector Cards",
            "Lot Description": "Picture(s) part of description. McDonald's limited edition Sheet A 1 of 3",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0405.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0405",
          },
          {
            "Lot Number": "0103",
            "Lot Title": "STYX LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0103.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0103",
          },
          {
            "Lot Number": "0406",
            "Lot Title": "John Elway #15 Beckett Graded 9 #315/750",
            "Lot Description": "Picture(s) part of description. 2000 Don Ross Preferred QBC Letterman Graded Series 1 of 300",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/7/0406.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0406",
          },
          {
            "Lot Number": "0407",
            "Lot Title": "2000 UD Encore #245 Jamal Lewis SGC Graded 10",
            "Lot Description": "Picture(s) part of description. Star Rookie with original package",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/7/0407.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0407",
          },
          {
            "Lot Number": "0104",
            "Lot Title": "JANIS JOPLIN GREATEST HITS VINYL LP",
            "Lot Description": "Picture(s) part of description. 1973 COLUMBIA RECORDS PC 82168",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0104.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0104",
          },
          {
            "Lot Number": "0408",
            "Lot Title": "2010 Antonio Brown Authentic Autograph A27",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0408.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0408",
          },
          {
            "Lot Number": "0409",
            "Lot Title": "1995 Classic Printers Proof Jerry Rice",
            "Lot Description": "Picture(s) part of description. Jerry Rice Printer Proof 1 of 499 / #2",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0409.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0409",
          },
          {
            "Lot Number": "0105",
            "Lot Title": "LEO SAYER RECORD LP",
            "Lot Description": "Picture(s) part of description. 1976 ENDLESS FLIGHT ALBUM. WARNER BROS RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0105.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0105",
          },
          {
            "Lot Number": "0410",
            "Lot Title": "Tri-Star 1987 TOPPS #365 Andre Reed",
            "Lot Description": "Picture(s) part of description. BCCG Mint 10 or better in original packaging.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0410.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0410",
          },
          {
            "Lot Number": "0411",
            "Lot Title": "Lot of 2 Russell Wilson RC Card / 8 x 10 Auto",
            "Lot Description": "Picture(s) part of description. (1) 2012 Russell Wilson Rookie Card #165 (2) Autographed 8 x 10 Photo with COA",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 45,
            "image": "/images/auctions/7/0411.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0411",
          },
          {
            "Lot Number": "0106",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. 1979 THE ELECTRIC HORSEMAN LETTERBOX EDITION",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0106.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0106",
          },
          {
            "Lot Number": "0412",
            "Lot Title": "Lot of 2 Merlin Olsen ",
            "Lot Description": "Picture(s) part of description. 1970 35 of 60 3D Superstars / 1991 Pro Football Hall of Fame #110",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0412.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0412",
          },
          {
            "Lot Number": "0413",
            "Lot Title": "Lot of 4 Vintage Vikings ",
            "Lot Description": "Picture(s) part of description. 1978 Chuck Foreman #400 / Alan Page Rookie RC Card #59 / Jim Marshall #103 & #107",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/7/0413.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0413",
          },
          {
            "Lot Number": "0107",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. THE HORSEMAN ON THE ROOF - WIDESCREEN 1990",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0107.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0107",
          },
          {
            "Lot Number": "0414",
            "Lot Title": "1993 Game Day Collector Cards Sheet B 2 of 3",
            "Lot Description": "Picture(s) part of description. McDonald's limited edition Sheet B 2 of 3",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0414.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0414",
          },
          {
            "Lot Number": "0415",
            "Lot Title": "Lot of 3 TOPPS All-American Autographs",
            "Lot Description": "Picture(s) part of description. A-TF A-CCE A-JDC",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0415.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0415",
          },
          {
            "Lot Number": "0108",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. GHOSTS OF MISSISSIPPI WIDESCREEN 1996",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0108.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0108",
          },
          {
            "Lot Number": "0416",
            "Lot Title": "Vince Young Rookie Premiere Materials",
            "Lot Description": "Picture(s) part of description. 2000 Absolute Memorabilia 269 of 849",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0416.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0416",
          },
          {
            "Lot Number": "0417",
            "Lot Title": "TOPPS Rookie Throw Back Relics Adam 'PacMan' Jones",
            "Lot Description": "Picture(s) part of description. Authentic Player Worn Jersey RT-AJ 2005",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0417.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0417",
          },
          {
            "Lot Number": "0109",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. LETTERBOX EDITION - EXOTICA ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0109.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0109",
          },
          {
            "Lot Number": "0418",
            "Lot Title": "1989 Pro-Set #509 Timm Rosenbach RC",
            "Lot Description": "Picture(s) part of description. Autograph Rookie Card",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0418.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0418",
          },
          {
            "Lot Number": "0419",
            "Lot Title": "Don Ross Elite 2009 Larry Johnson #25",
            "Lot Description": "Picture(s) part of description. Chain Reaction Authentic Jersey 218-299",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0419.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0419",
          },
          {
            "Lot Number": "0110",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. WIDESCREEN EDITION - EXTENDED PLAY - GYPSY ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0110.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0110",
          },
          {
            "Lot Number": "0420",
            "Lot Title": "Jerry Rice 1993 Game Day Collectors Card",
            "Lot Description": "Picture(s) part of description. McDonalds Limited Edition Sheet C 3 or 3",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0420.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0420",
          },
          {
            "Lot Number": "0421",
            "Lot Title": "2001 Fleer / SkyBox Steve Young Showcase Card",
            "Lot Description": "Picture(s) part of description. Authentic NFL Game Worn Jersey",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0421.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0421",
          },
          {
            "Lot Number": "0111",
            "Lot Title": "HEART 45 RPM LP",
            "Lot Description": "Picture(s) part of description. 1985 CAPITOL RECORDS. HEART NEVER",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0111.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0111",
          },
          {
            "Lot Number": "0422",
            "Lot Title": "Lot of 3 Reggie Bush 2 Sage Game Exclusive Jerseys Card",
            "Lot Description": "Picture(s) part of description. #TRR-RB Turkey Red Numbered 145/399",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0422.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0422",
          },
          {
            "Lot Number": "0423",
            "Lot Title": "2007 Game Worn Jersey Card Steve McNair ",
            "Lot Description": "Picture(s) part of description CA--19 Numbered 173/200",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0423.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0423",
          },
          {
            "Lot Number": "0112",
            "Lot Title": "DIRE STRAITS 45 RPM RECORD",
            "Lot Description": "Picture(s) part of description. MONEY FOR NOTHING",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0112.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0112",
          },
          {
            "Lot Number": "0424",
            "Lot Title": "2003 Leaf Certified Steve Smith #16 Card",
            "Lot Description": "Picture(s) part of description. Authentic Game Worn Jersey Card Number 6/50",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0424.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0424",
          },
          {
            "Lot Number": "0425",
            "Lot Title": "2000 EDGE Graded Original Box",
            "Lot Description": "Picture(s) part of description. 2000 PSA GEM Mint 10 Kurt Warner #144 Uncirculated",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/7/0425.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0425",
          },
          {
            "Lot Number": "0113",
            "Lot Title": "ASIA 45 RPM LP",
            "Lot Description": "Picture(s) part of description. 1982 HEAT OF THE MOMENT ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0113.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0113",
          },
          {
            "Lot Number": "0426",
            "Lot Title": "1993 Raiders Game Day Cards",
            "Lot Description": "Picture(s) part of description. McDonalds Limited Edition Sheet B 2 or 3",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0426.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0426",
          },
          {
            "Lot Number": "0427",
            "Lot Title": "Lot of 2 Emmanuel Sanders Numbered Cards",
            "Lot Description": "Picture(s) part of description. (1) TOPPS Unriveled #146 Rookie RC Card Signed #129/680 (2)2010 Certified Freshman Fabric #282 Authenic Autographed Numbered 138/699",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/7/0427.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0427",
          },
          {
            "Lot Number": "0114",
            "Lot Title": "HEART 45 LP THESE DREAMS",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0114.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0114",
          },
          {
            "Lot Number": "0428",
            "Lot Title": "Marshall Faulk CGG #MF28-A",
            "Lot Description": "Picture(s) part of description. 2000 LEAF Certified Authentic Game Worn Away Jersey Numbered 53/100",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0428.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0428",
          },
          {
            "Lot Number": "0429",
            "Lot Title": "Lot of 2 Game Day ",
            "Lot Description": "Picture(s) part of description. (1) TOPPS Certified Autograph Issue Jahvid Best (2) Game Worn Jersey Relic Miles Austin",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0429.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0429",
          },
          {
            "Lot Number": "0115",
            "Lot Title": "BLONDIE CALL ME. 45 LP RECORD",
            "Lot Description": "Picture(s) part of description. 1980 THEME FROM PARAMOUNT PICTURES AMERICAN GIGOLO",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0115.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0115",
          },
          {
            "Lot Number": "0430",
            "Lot Title": "Lot of 2 Flair Showcase Stitches",
            "Lot Description": "Picture(s) part of description. Edgerrin James / Matt Leinart Rookie Card",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0430.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0430",
          },
          {
            "Lot Number": "0431",
            "Lot Title": "2005 LEAF Limited Phenoms",
            "Lot Description": "Picture(s) part of description. Eric Shelton Event Worn Jersey / Auto Numbered 1/25",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0431.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0431",
          },
          {
            "Lot Number": "0116",
            "Lot Title": "GOLDEN REPLICAS OF UNITED STATES STAMPS",
            "Lot Description": "Picture(s) part of description. BOOK WITH FIRST EDITION PROOF REPLICAS ON A GLEAMING SURFACE OF 22 CARAT GOLD 1ST DAY ISSUES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/6/0116.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0116",
          },
          {
            "Lot Number": "0432",
            "Lot Title": "TOPPS Platinum Refractor #ARP-RM Rashard Mendenhall",
            "Lot Description": "Picture(s) part of description. Authentic Game Worn Jersey Patch TOPP Certified Autograph Issue Numbered 080/ 350",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0432.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0432",
          },
          {
            "Lot Number": "0433",
            "Lot Title": "2010 Prestige Connections Game Worn Jerseys Card",
            "Lot Description": "Picture(s) part of description. Matt Ryan and Rodney White Numbered 060/250",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0433.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0433",
          },
          {
            "Lot Number": "0117",
            "Lot Title": "JULIAN LENON ALBUM LP",
            "Lot Description": "Picture(s) part of description. 1984 VALOTTE ATLANTIC RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0117.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0117",
          },
          {
            "Lot Number": "0434",
            "Lot Title": "Playoff Signature Proof #138 Card",
            "Lot Description": "Picture(s) part of description. #138 Chad Greenway Authentic Signature numbered 054/150",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0434.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0434",
          },
          {
            "Lot Number": "0435",
            "Lot Title": "TOPPS Prime Marcus Easley Numbered PLS-ME Card",
            "Lot Description": "Picture(s) part of description. Authentic Autograph and 4 pieces of Player Worn Jersey Numbered 358/399",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0435.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0435",
          },
          {
            "Lot Number": "0118",
            "Lot Title": "BILLY JOEL LP ALBUM",
            "Lot Description": "Picture(s) part of description. 1980 GLASS HOUSES CBS RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0118.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0118",
          },
          {
            "Lot Number": "0436",
            "Lot Title": "Brett Favre Authentic Jersey Piece ",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0436.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0436",
          },
          {
            "Lot Number": "0437",
            "Lot Title": "Authentic Jersey and Card Set Dan Marino",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0437.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0437",
          },
          {
            "Lot Number": "0119",
            "Lot Title": "BARBRA STREISAND LP",
            "Lot Description": "Picture(s) part of description. 1977 SUPERMAN ALBUM CBS RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0119.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0119",
          },
          {
            "Lot Number": "0438",
            "Lot Title": "Kurt Warner 8 x 10 Autographed Photo Plus Authentic Jersey & Card Set",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 45,
            "image": "/images/auctions/7/0438.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0438",
          },
          {
            "Lot Number": "0439",
            "Lot Title": "TOPPS Cris Collingsworth #37 Card",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0439.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0439",
          },
          {
            "Lot Number": "0120",
            "Lot Title": "DOUBLE FANTASY ALBUM",
            "Lot Description": "Picture(s) part of description. 1980 JOHN LENNON AND YOKO ONO. LENONO MUSCI. COVER WATER STAINED DAMAGE.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0120.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0120",
          },
          {
            "Lot Number": "0440",
            "Lot Title": "Vintage 1970 Jack Snow #44 Card",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0440.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0440",
          },
          {
            "Lot Number": "0441",
            "Lot Title": "2010 Rookies & Stars Freddie Barnes #196 Card ",
            "Lot Description": "Picture(s) part of description. RC Rookie Card #079/299",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0441.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0441",
          },
          {
            "Lot Number": "0121",
            "Lot Title": "JAMES GANG RIDES AGAIN VINYL LP",
            "Lot Description": "Picture(s) part of description. 1972 MCA RECORDS ABCS-711",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0121.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0121",
          },
          {
            "Lot Number": "0442",
            "Lot Title": "Bowman Sterling Jacoby Ford Rookie Card",
            "Lot Description": "Picture(s) part of description. Bowman Refractor BSA-JF Rookie RC Card Autograph #12/50",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0442.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0442",
          },
          {
            "Lot Number": "0443",
            "Lot Title": "2010 Certified Mike Williams Rookie #296 Card",
            "Lot Description": "Picture(s) part of description. Freshman Fabric with Authentic Autograph numbered 216/699",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0443.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0443",
          },
          {
            "Lot Number": "0122",
            "Lot Title": "CARLY SIMON COME UPSTAIRS VINYL LP",
            "Lot Description": "Picture(s) part of description. 1980 WARNERS BROS ALBUM",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0122.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0122",
          },
          {
            "Lot Number": "0444",
            "Lot Title": "Authentic Jersey and Card Set Jerry Rice",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0444.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0444",
          },
          {
            "Lot Number": "0445",
            "Lot Title": "Sealed PSA Gem Mint 10 Dan Marino Numbered 112",
            "Lot Description": "Picture(s) part of description. 1 of 5000 Uncirculated",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/7/0445.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0445",
          },
          {
            "Lot Number": "0123",
            "Lot Title": "JACKSON BROWN - RUNNING ON EMPTY VINYL LP",
            "Lot Description": "Picture(s) part of description. 1977 ELEKTRA/ASYLUM RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0123.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0123",
          },
          {
            "Lot Number": "0446",
            "Lot Title": "Beckett Graded 9 A.J. Hawk Card",
            "Lot Description": "Picture(s) part of description. 2006 Score Rookie Card #373",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0446.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0446",
          },
          {
            "Lot Number": "0447",
            "Lot Title": "TOPPS Chrome Drew Brees #C30",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0447.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0447",
          },
          {
            "Lot Number": "0124",
            "Lot Title": "THE BIG CHILL ALBUM LP",
            "Lot Description": "Picture(s) part of description. 1984 MOTOWN RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0124.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0124",
          },
          {
            "Lot Number": "0448",
            "Lot Title": "Matt Paradis Rookie RC Card Denver Broncos",
            "Lot Description": "Picture(s) part of description. Superbowl 50 Champion Only NFL Rookie Card",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0448.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0448",
          },
          {
            "Lot Number": "0449",
            "Lot Title": "PANINI Contenders 2018 Draft Picks RC Card",
            "Lot Description": "Picture(s) part of description. Leighton Vander Esch Autographed #299 Rookie RC Card",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0449.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0449",
          },
          {
            "Lot Number": "0125",
            "Lot Title": "THE BLUES BROTHERS ALBUM",
            "Lot Description": "Picture(s) part of description. 1980 ORIGINAL SOUNDTRACK RECORDING",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0125.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0125",
          },
          {
            "Lot Number": "0450",
            "Lot Title": "Arnold Donald RC Rookie Card #102",
            "Lot Description": "Picture(s) part of description. 25 Card Rookie Pack",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/7/0450.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/LEGENDS-OF-THE-BALL-AUCTION-6-FOOTBALL-CARDS/event-catalog/248763#lot-image-0450",
          },
          {
            "Lot Number": "0126",
            "Lot Title": "RUN BABY RUN COMIC BOOK",
            "Lot Description": "Picture(s) part of description. ALL NEW COMIC",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 2,
            "image": "/images/auctions/6/0126.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0126",
          },
          {
            "Lot Number": "0127",
            "Lot Title": "COMIC BOOK SAD SACK 12 CENT ISSUE",
            "Lot Description": "Picture(s) part of description. HARVEY COMICS #202",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 2,
            "image": "/images/auctions/6/0127.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0127",
          },
          {
            "Lot Number": "0128",
            "Lot Title": "COMIC BOOKS GOLD KEY BUGS BUNNY",
            "Lot Description": "Picture(s) part of description. 12 CENT COMIC BOOK",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 2,
            "image": "/images/auctions/6/0128.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0128",
          },
          {
            "Lot Number": "0129",
            "Lot Title": "COMIC BOOKS LOT OF 2",
            "Lot Description": "Picture(s) part of description. VINTAGE ARCHIE COMIC BOOKS - READER COPIES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 2,
            "image": "/images/auctions/6/0129.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0129",
          },
          {
            "Lot Number": "0130",
            "Lot Title": "COMIC BOOKS LOT OF 4",
            "Lot Description": "Picture(s) part of description. VINTAGE COMIC BOOKS - READER COPIES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0130.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0130",
          },
          {
            "Lot Number": "0131",
            "Lot Title": "JANIS JOPLIN PEARL VINYL LP RECORD",
            "Lot Description": "Picture(s) part of description. JANIS JOPLIN FULL TILT BOOGIE 1971 COLUMBIA RECORDS PC30322",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0131.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0131",
          },
          {
            "Lot Number": "0132",
            "Lot Title": "BILLY JOEL LOT OF 3 VINYL LP ALBUM",
            "Lot Description": "Picture(s) part of description. (1) AN INNOCENT MAN (2) THE STRANGER (3) GLASS HOUSES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0132.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0132",
          },
          {
            "Lot Number": "0133",
            "Lot Title": "AIR SUPPLY LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) THE ONE THAT YOU LOVE (2) LOST IN LOVE ARISTA RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0133.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0133",
          },
          {
            "Lot Number": "0134",
            "Lot Title": "REO SPEEDWAGON LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) NINE LIVES (2) WHEELS ARE TURNING. EPIC RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0134.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0134",
          },
          {
            "Lot Number": "0135",
            "Lot Title": "TEN YEARS AFTER A SPACE IN TIME VINYL LP",
            "Lot Description": "Picture(s) part of description. COLUMBIA RECORDS 30801 1971 IN STEREO",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0135.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0135",
          },
          {
            "Lot Number": "0136",
            "Lot Title": "LEO SAYER VINYL LP",
            "Lot Description": "Picture(s) part of description. 1977 THUNDER IN MY HEART ALBUM",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0136.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0136",
          },
          {
            "Lot Number": "0137",
            "Lot Title": "BOZ SCAGGS VINYL LP LOT OF 3",
            "Lot Description": "Picture(s) part of description. (1) SILK DEGREES (2) DOWN TWO THEN LEFT (3) SLOW DANCER",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0137.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0137",
          },
          {
            "Lot Number": "0138",
            "Lot Title": "HUEY LEWIS & THE NEWS VINYL LP",
            "Lot Description": "Picture(s) part of description. SPORTS. 1983 CHRYSALIS ECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0138.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0138",
          },
          {
            "Lot Number": "0139",
            "Lot Title": "PETER FRAMPTON LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) FRAMPTON COMES ALIVE (2) 1977 I AM IN YOU ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0139.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0139",
          },
          {
            "Lot Number": "0140",
            "Lot Title": "STONEGROUND LOG OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) HEARTS OF STONE 1978 WARNER BROS (2) FLAT OUT 1976 FLAT OUT RECORDS COPYRIGHT",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0140.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0140",
          },
          {
            "Lot Number": "0141",
            "Lot Title": "DIGITAL LASERDISC ",
            "Lot Description": "Picture(s) part of description. 1994 DELUXE THEATRICAL PRESENTATION DAS BOOT GERMAN WITH ENGLISH SUB TITLES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0141.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0141",
          },
          {
            "Lot Number": "0142",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. HARRISON FORD IN AIRFORCE ONE 1997 DELUXE WIDESCREEN PRESENTATOIN",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0142.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0142",
          },
          {
            "Lot Number": "0143",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. SCHWARZENEGGER IN TOTAL RECALL. 1990 DIGITAL STEREO SURROUND SOUND",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0143.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0143",
          },
          {
            "Lot Number": "0144",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. VAN DAMME IN SUDDEN DEATH. 1996 LETTERBOX MCA UNIVERSAL",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0144.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0144",
          },
          {
            "Lot Number": "0145",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. VAN DAMME / DOLPH LUNDGREN IN UNIVERSAL SOLDIER. PARTIAL ORIGINAL SHRINK WRAP 1992",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0145.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0145",
          },
          {
            "Lot Number": "0146",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. SCALY THE LIZARD",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0146.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0146",
          },
          {
            "Lot Number": "0147",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. CHOCOLATE THE MOOSE",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0147.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0147",
          },
          {
            "Lot Number": "0148",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. STINGER THE SCORPION",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0148.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0148",
          },
          {
            "Lot Number": "0149",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. LUCY THE GOOSE",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0149.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0149",
          },
          {
            "Lot Number": "0150",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. RAINBOW THE CHAMELEON",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0150.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0150",
          },
          {
            "Lot Number": "0151",
            "Lot Title": "GHOST HTF VHS",
            "Lot Description": "Picture(s) part of description. 1990 MCDONALD'S PROMO EDITION. RARE VHS TAPE HI-FI STEREO DOLBY SURROUND SOUND",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/6/0151.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0151",
          },
          {
            "Lot Number": "0152",
            "Lot Title": "SCREAM RARE VHS TAPE",
            "Lot Description": "Picture(s) part of description. ORIGINAL SLIP COVER WESTCRAVEN. HARD TO FIND HORROR MOVIE",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/6/0152.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0152",
          },
          {
            "Lot Number": "0153",
            "Lot Title": "CREATURE FROM THE HAUNTED SEA HTF VHS TAPE",
            "Lot Description": "Picture(s) part of description. HARD TO FIND VHS TAPE. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0153.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0153",
          },
          {
            "Lot Number": "0154",
            "Lot Title": "SCARY MOVIE 2 VHS TAPE HTF",
            "Lot Description": "Picture(s) part of description. COMEDY HORROR FLICK WITH ORIGINAL SHRINK WRAP",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0154.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0154",
          },
          {
            "Lot Number": "0155",
            "Lot Title": "MARS ATTACKS! VHS TAPE",
            "Lot Description": "Picture(s) part of description. WITH JACK NICHOLSON. HARD TO FIND SCI-FI COMEDY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0155.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0155",
          },
          {
            "Lot Number": "0156",
            "Lot Title": "REBEL WILSON AUTOGRAPH COA",
            "Lot Description": "Picture(s) part of description. AUTOGRAPHED 2019 INSTYLE MAGAZINE",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/6/0156.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0156",
          },
          {
            "Lot Number": "0157",
            "Lot Title": "LOT OF 2 MARVEL COMICS",
            "Lot Description": "Picture(s) part of description. THE WEST COAST AVENGERS GIANT SIZED ANNUAL NO. 2 1987 AND WEST COAST AVENGERS VS. THE RANGERS 25TH ANNIVERSARY NO. 8",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0157.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0157",
          },
          {
            "Lot Number": "0158",
            "Lot Title": "MARVEL COMICS GROUP",
            "Lot Description": "Picture(s) part of description. AVENGERS LOG #1",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0158.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0158",
          },
          {
            "Lot Number": "0159",
            "Lot Title": "MARVEL COMICS LOT OF 2 CLOAK & DAGGER",
            "Lot Description": "Picture(s) part of description. (1) GUEST STARRING SPIDER-MAN NO. 17 (2) GHOST RIDER & SPIDER-MAN JOIN CLOAK & DAGGER NO. 18",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0159.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0159",
          },
          {
            "Lot Number": "0160",
            "Lot Title": "LOT OF 4 MIXED COMIC BOOKS",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0160.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0160",
          },
          {
            "Lot Number": "0161",
            "Lot Title": "CHICAGO LOT OF 2 VINYL LP ALBUMS",
            "Lot Description": "Picture(s) part of description. CHICAGO SIXTEEN 1982 WARNER BROS RECORDS & IF YOU LEAVE ME NOW 1983 COLUMBIA RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0161.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0161",
          },
          {
            "Lot Number": "0162",
            "Lot Title": "THE JIM CROCE COLLECTION VINYL LP RECORD",
            "Lot Description": "Picture(s) part of description. 1977 20 GREATEST HITS. TVLP-77024",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0162.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0162",
          },
          {
            "Lot Number": "0163",
            "Lot Title": "GORDON LIGHTFOOT VINYL LP ",
            "Lot Description": "Picture(s) part of description. GORD'S GOLD. 1975 WARNER BROS GATEFOLD ALBUM",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0163.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0163",
          },
          {
            "Lot Number": "0164",
            "Lot Title": "EDDIE MONEY VINYL LP ",
            "Lot Description": "Picture(s) part of description. 1978 LIFE FOR THE TAKING. COLUMBIA RECORDS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0164.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0164",
          },
          {
            "Lot Number": "0165",
            "Lot Title": "LEO SAYER VINYL LP",
            "Lot Description": "Picture(s) part of description. 1980 LIVING IN A FANTASY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0165.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0165",
          },
          {
            "Lot Number": "0166",
            "Lot Title": "CHUCK TAYLOR CONVERSE ALL-STAR ",
            "Lot Description": "Picture(s) part of description. HIGH TOP BASKETBALL SHOES SIZE 12 WHITE/RED/BLUE SPHICT ALLSTAR NEW/OLD STOCK NEVER WORN ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 300,
            "image": "/images/auctions/6/0166.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0166",
          },
          {
            "Lot Number": "0167",
            "Lot Title": "GREASE LEATHER JACKET COVER WITH DVD",
            "Lot Description": "Picture(s) part of description. GREASE ROCKING RYDELL EDITION",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/6/0167.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0167",
          },
          {
            "Lot Number": "0168",
            "Lot Title": "GARTH BROOKS FACTORY SEALED DVD SET",
            "Lot Description": "Picture(s) part of description. 5 DISC DVD SET BONUS SONGS AND PHOTO GALLERY. LIMITED EDITION TEN",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/6/0168.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0168",
          },
          {
            "Lot Number": "0169",
            "Lot Title": "BOB MARLEY 4 CD SET WITH BOOKLET",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0169.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0169",
          },
          {
            "Lot Number": "0170",
            "Lot Title": "THE DOORS 2 VHS LOT",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0170.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0170",
          },
          {
            "Lot Number": "0171",
            "Lot Title": "TITANIC VHS TAPES",
            "Lot Description": "Picture(s) part of description. SET OF 2 1998 VHS HI-FI STEREO",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0171.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0171",
          },
          {
            "Lot Number": "0172",
            "Lot Title": "LORD OF THE RINGS VHS TAPES",
            "Lot Description": "Picture(s) part of description. RETURN OF THE KING. SET OF 2 ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0172.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0172",
          },
          {
            "Lot Number": "0173",
            "Lot Title": "BRAVEHEART (MEL GIBSON) VHS TAPES",
            "Lot Description": "Picture(s) part of description. 1995 PARAMOUNT 2 VHS HI-FI STEREO TAPES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0173.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0173",
          },
          {
            "Lot Number": "0174",
            "Lot Title": "GONE WITH THE WIND VHS TAPES",
            "Lot Description": "Picture(s) part of description. 1939 DIGITAL VIDEO TRANSFER 2 VHS TAPES",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0174.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0174",
          },
          {
            "Lot Number": "0175",
            "Lot Title": "THE MOODY BLUES OUT OF THIS WORLD VINYL LP",
            "Lot Description": "Picture(s) part of description. LP MANUFACTURED IN FRANCE 1979 K-TELL INTL.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0175.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0175",
          },
          {
            "Lot Number": "0176",
            "Lot Title": "THE MOODY BLUES EVERY GOOD BOY DESERVES FAVOUR VINYL LP",
            "Lot Description": "Picture(s) part of description. 1971 DECCA RECORD CO LTD GATEFOLD WITH ORIGINAL INNER SLEEVE",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0176.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0176",
          },
          {
            "Lot Number": "0177",
            "Lot Title": "THE MOODY BLUES TO OUR CHILDREN'S CHILDREN'S CHILDREN VINYL LP",
            "Lot Description": "Picture(s) part of description. 1969 THRESHHOLD MUSIC LTD",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0177.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0177",
          },
          {
            "Lot Number": "0178",
            "Lot Title": "LASERDISC - ALIENS",
            "Lot Description": "Picture(s) part of description. ALIENS. 1995 WIDESCREEN EDITION",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0178.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0178",
          },
          {
            "Lot Number": "0179",
            "Lot Title": "LASERDISC - CLOSE ENCOUNTERS OF THE THIRD KIND",
            "Lot Description": "Picture(s) part of description. SPECIAL EDITION EXTENDED PLAY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0179.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0179",
          },
          {
            "Lot Number": "0180",
            "Lot Title": "NEIL DIAMOND LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) LIVE AT THE GREEK THEATRE (2) CLASSICS THE EARLY YEARS ORIGINAL HITS RECORDINGS (3) PRIMITIVE (4) GREATEST HITS BLPS-219-STEREO",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0180.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0180",
          },
          {
            "Lot Number": "0181",
            "Lot Title": "NEIL DIAMOND LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0181.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0181",
          },
          {
            "Lot Number": "0182",
            "Lot Title": "SWEET LEVEL HEADED VINYL LP",
            "Lot Description": "Picture(s) part of description. 1977 CAPITOL RECORDS SKAO-11744",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0182.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0182",
          },
          {
            "Lot Number": "0183",
            "Lot Title": "LITTLE RIVER BAND LOT OF 2 VINYL LP MIXED EASY ROCK",
            "Lot Description": "Picture(s) part of description. LITTLE RIVER BANK TIME EXPOSURE & THE ELVIN BISHOP BANK - ROCK MY SOUL",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0183.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0183",
          },
          {
            "Lot Number": "0184",
            "Lot Title": "R & R RECORDS LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. JIM STEINMAN BAD FOR GOOD & POINT BLANK - THE HARD WAY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0184.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0184",
          },
          {
            "Lot Number": "0185",
            "Lot Title": "MOTHER GOOSE RHYMES BOOK & RECORD",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0185.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0185",
          },
          {
            "Lot Number": "0186",
            "Lot Title": "THREE LITTLE PIGS BOOK & RECORD",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0186.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0186",
          },
          {
            "Lot Number": "0187",
            "Lot Title": "JACK AND THE BEANSTALK BOOK & RECORD",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0187.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0187",
          },
          {
            "Lot Number": "0188",
            "Lot Title": "CASPER THE FRIENDLY GHOST BOOK & RECORD",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/6/0188.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0188",
          },
          {
            "Lot Number": "0189",
            "Lot Title": "CARDED HOT WHEELS LOT OF 4",
            "Lot Description": "Picture(s) part of description. TWO RED LINE SERIES & TWO REALISTIX. LOT OF 2 WITH 1 SHORT CARD",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0189.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0189",
          },
          {
            "Lot Number": "0190",
            "Lot Title": "CARDED 57 CHEVY LOT OF 4",
            "Lot Description": "Picture(s) part of description. ORIGINAL HOT WHEELS 57 CHEVY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0190.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0190",
          },
          {
            "Lot Number": "0191",
            "Lot Title": "CARDED 57 CHEVY LOT OF 4",
            "Lot Description": "Picture(s) part of description. ORIGINAL HOT WHEELS 57 CHEVY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0191.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0191",
          },
          {
            "Lot Number": "0192",
            "Lot Title": "CARDED 57 CHEVY LOT OF 4",
            "Lot Description": "Picture(s) part of description. ORIGINAL HOT WHEELS 57 CHEVY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/6/0192.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0192",
          },
          {
            "Lot Number": "0193",
            "Lot Title": "HOT WHEELS JONES SODA RV",
            "Lot Description": "Picture(s) part of description. NO. 02596 OF 05000",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/6/0193.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0193",
          },
          {
            "Lot Number": "0194",
            "Lot Title": "1991 HOT WHEELS BYWAYMAN",
            "Lot Description": "Picture(s) part of description. ORIGINAL 1991 CARDED",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0194.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0194",
          },
          {
            "Lot Number": "0195",
            "Lot Title": "ORIGINAL HIRAKERS HOT WHEELS",
            "Lot Description": "Picture(s) part of description. UN-PUNCHED CARD 40'S WOODY 1979 MADE IN HONG KONG",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/6/0195.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0195",
          },
          {
            "Lot Number": "0196",
            "Lot Title": "MIXED LOT OF 2 MOTOWN VINYL LPS",
            "Lot Description": "Picture(s) part of description. (1) LIONEL RICHIE CAN'T SLOW DOWN (2) MARILYN MCCOO & BILLIE DAVIS JR. THE TWO OF US",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0196.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0196",
          },
          {
            "Lot Number": "0197",
            "Lot Title": "MOTOWN - POINTER SISTERS LOT OF 2 VINYL LPS",
            "Lot Description": "Picture(s) part of description. CONTACT AND BREAKOUT",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0197.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0197",
          },
          {
            "Lot Number": "0198",
            "Lot Title": "LOT OF 4 EASY LISTENING VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) ENGLAND DAN & JOHN FORD COLEY-SOME THINGS DON'T COME EASY (2) SEALS & CROFTS COLLECTION (3) BILLY VAUGHN PEARLY SHELLS (4) FIREFALL ELAN",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0198.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0198",
          },
          {
            "Lot Number": "0199",
            "Lot Title": "LOT OF 4 EASY LISTENING VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) JUSTIN HAYWARD - SONGWRITER (2) CORY HART - BOY IN THE BOX (3) KENNY G - SILHOUETTE (4) CHRIS REAR - WHATEVER HAPPENED TO BENNY SANTINY",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0199.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0199",
          },
          {
            "Lot Number": "0200",
            "Lot Title": "LAURA BRANIGAN LOT OF 2 VINYL LPS",
            "Lot Description": "Picture(s) part of description. (1) SELF-CONTROL & (2) BRANIGAN 2",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/6/0200.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Susan-Payne-Estate/event-catalog/247948#lot-image-0200",
          },
        ],
        onOpen: onOpen,
        open: openSection === 'auctions',
        keyname: 'auctions',
      }, // auctions
    ]
  }

  function onOpen(label) {
    if (openSection !== label) {
      setOpenSection(label)
    }
    else {
      setOpenSection('');
    }
  }

  return (
    <div>
      <Meta {...propList.meta} />
      <Hero {...propList.hero}/>
      {propList.AuctionSections.map((section, index) => {
        return (
          <AuctionCollapsible key={'section-'+index} {...section} />
        )
      })}
    </div>
  )
}
