import React, { useEffect, useState } from 'react'
import AuctionCollapsible from 'src/components/AuctionCollapsible'
import Hero from 'src/components/Hero'
import Meta from 'src/components/Meta'

export default function Home() {
  
  const [openSection, setOpenSection] = useState('auctions');

  let propList = {
    meta: {
      title: 'DJ\'s Auction House',
      description: 'DJ\'s Auction House is selling everything you could possibly need or want! Get in quick to see our latest items!',
      image: {
        src: '/images/home/hero.jpg',
        alt: 'Hero',
        width: 589,
        height: 295,
      },
    },
    hero: {
      title: `DJ's Auction House`,
      backgroundImage: '/images/hero/hero.jpg',
    },
    AuctionSections: [
      {
        title: 'Auctions',
        auctions: [
          {
            "Lot Number": "0101",
            "Lot Title": "JANIS JOPLIN - 1967 RECORD",
            "Lot Description": "Picture(s) part of description. BIG BROTHER & THE HOLDING CO. WITH JANIS JOPLIN LEAD SINGER. CHEAP THRILLS PC 9700 IN STEREO",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 30,
            "image": "/images/auctions/3/0101.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A1",
            "Lot Title": "Jim Beam Blue VW Decanter",
            "Lot Description": "Picture(s) part of description. Vintage 1970's VW Volkswagen Beettle Bug Blue Jim Beam Whiskey Decanter Car w/paper. Never been filled.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A1.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0102",
            "Lot Title": "LOT OF 3 BOB SEGER & THE SILVER BULLET BAND VINYL LP",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0102.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A2",
            "Lot Title": "Jim Beam Red VW Decanter",
            "Lot Description": "Picture(s) part of description. Vintage 1970's VW Volkswagen Beettle Bug Red Jim Beam Whiskey Decanter Car w/paper. Never been filled.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A2.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0103",
            "Lot Title": "STYX LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0103.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A3",
            "Lot Title": "Orange VW Ertl Custom Diecast Bank",
            "Lot Description": "Picture(s) part of description. Very Rare Beetle Sedan Custom 2000 Beam Bottle Collectors Convention. Bank with key. Never used. Back bumper broke.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A3.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0104",
            "Lot Title": "JANIS JOPLIN GREATEST HITS VINYL LP",
            "Lot Description": "Picture(s) part of description. 1973 COLUMBIA RECORDS PC 82168",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0104.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A4",
            "Lot Title": "Head East Original LP VG. Vinyl Record",
            "Lot Description": "AM Records SP-4579. Picture(s) part of description.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A4.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0105",
            "Lot Title": "STYX CORNERSTONE VINYL LP",
            "Lot Description": "Picture(s) part of description. 1979 A&M RECORDS SP-3711",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0105.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A5",
            "Lot Title": "Meatloaf Original Promo LP VG Vinyl Record",
            "Lot Description": "1986 Promotional Album. Picture(s) part of description.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A5.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0106",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. 1979 THE ELECTRIC HORSEMAN LETTERBOX EDITION",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0106.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A6",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A6.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0107",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. THE HORSEMAN ON THE ROOF - WIDESCREEN 1990",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0107.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A7",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A7.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0108",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. GHOSTS OF MISSISSIPPI WIDESCREEN 1996",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0108.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A8",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A8.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0109",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. LETTERBOX EDITION - EXOTICA ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0109.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A9",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A9.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0110",
            "Lot Title": "DIGITAL LASERDISC FACTORY SEALED",
            "Lot Description": "Picture(s) part of description. WIDESCREEN EDITION - EXTENDED PLAY - GYPSY ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0110.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A10",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A10.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0111",
            "Lot Title": "NEW WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. CLOUDSTEPPERS BY CLARKS SIZE 8 ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/3/0111.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A11",
            "Lot Title": "Silver Peace Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. Genuine Peace Dollar 1927",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 40,
            "image": "/images/auctions/4/A11.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0112",
            "Lot Title": "NEW WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. MICHAEL KORS LEOPARD DESIGN SIZE 8 WILDCAT",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 60,
            "image": "/images/auctions/3/0112.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A12",
            "Lot Title": "Silver Peace Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1927 Genuine Peace Dollar",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/4/A12.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0113",
            "Lot Title": "NEW WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. BLACK EASY SPIRIT SIZE 7 1/2 ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/3/0113.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A13",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1896-P Genuine Silver Dollar",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 75,
            "image": "/images/auctions/4/A13.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0114",
            "Lot Title": "NEW WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. BLACK LEATHER MATADORS EASY SPIRIT SIZE 8",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0114.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A14",
            "Lot Title": "Authentic Coin",
            "Lot Description": "Picture(s) part of description.1999 Silver Proof",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/4/A14.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0115",
            "Lot Title": "NEW WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. TAN LEATHER MATADORS SIZE 8",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0115.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A15",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1971 40% Silver Uncirculated BU",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/4/A15.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0116",
            "Lot Title": "GOLDEN REPLICAS OF UNITED STATES STAMPS",
            "Lot Description": "Picture(s) part of description. BOOK WITH FIRST EDITION PROOF REPLICAS ON A GLEAMING SURFACE OF 22 CARAT GOLD 1ST DAY ISSUES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0116.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A16",
            "Lot Title": "CATS Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A16.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0117",
            "Lot Title": "PORCELAIN DOLL",
            "Lot Description": "Picture(s) part of description. KIMBERLY LIMITED EDITION OF FINE PORCELAIN DOLLS WITH ORIGINAL TAGS BY TIMELESS TREASURES.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0117.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A17",
            "Lot Title": "The Replacements VHS Sealed",
            "Lot Description": "Picture(s) part of description. Factory Sealed with Watermarks VHS The Replacements",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A17.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0118",
            "Lot Title": "PORCELAIN DOLL",
            "Lot Description": "Picture(s) part of description. BABY'S DREAM WITH CERTIFICATE OF AUTHENTICITY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0118.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A18",
            "Lot Title": "Miami Rhapsody Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A18.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0119",
            "Lot Title": "PORCELAIN DOLL",
            "Lot Description": "Picture(s) part of description. BABY'S DREAM WITH CERTIFICATE OF AUTHENTICITY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0119.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A19",
            "Lot Title": "Green Card Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A19.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0120",
            "Lot Title": "DUCKHOUSE HEIRLOOM DOLLS",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0120.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A20",
            "Lot Title": "My Best Friends Wedding Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A20.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0121",
            "Lot Title": "JAMES GANG RIDES AGAIN VINYL LP",
            "Lot Description": "Picture(s) part of description. 1972 MCA RECORDS ABCS-711",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0121.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A21",
            "Lot Title": "Michael Jackson Original LP VG Vinyl Record",
            "Lot Description": "Picture(s) part of description. 1982 Thriller",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A21.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0122",
            "Lot Title": "DR. HOOKS GREATEST HITS VINYL LP",
            "Lot Description": "Picture(s) part of description. 1980 CAPITOL RECORDS S00-12122",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0122.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A22",
            "Lot Title": "Alice Cooper Original LP VG Vinyl Record",
            "Lot Description": "Picture(s) part of description. 1973 Muscle Of Love. Warner Bros Records. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/4/A22.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0123",
            "Lot Title": "JACKSON BROWN - RUNNING ON EMPTY VINYL LP",
            "Lot Description": "Picture(s) part of description. 1977 ELEKTRA/ASYLUM RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0123.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A23",
            "Lot Title": "The Moody Blues Original LP VG Vinyl Record",
            "Lot Description": "Picture(s) part of description. To Our Children's Children's Children. Distributed by London Records.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A23.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0124",
            "Lot Title": "STEVE PERRY - STREET TALK VINYL LP",
            "Lot Description": "Picture(s) part of description. 1984 CBS INC. COLUMBIA RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0124.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A24",
            "Lot Title": "Scorpions Lovedrive Viny LP",
            "Lot Description": "Picture(s) part of description. Vinyl LP 1979 Phonogram Album inscribed & stamped on Vinyl SRM-1-3795 with Original Inner Sleeve",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A24.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0125",
            "Lot Title": "BOB DYLAN - SLOW TRAIN COMING VINYL LP",
            "Lot Description": "Picture(s) part of description. 1979 COLUMBIA RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0125.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A25",
            "Lot Title": "Get the Knack by the Knack",
            "Lot Description": "Picture(s) part of description. 1979 Capitol Records. Etched on vinyl SO-1-11948Z2 #2 with Original Inner Sleeve",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A25.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0126",
            "Lot Title": "COMIC BOOKS LOT OF 4",
            "Lot Description": "Picture(s) part of description. VINTAGE ARCHIE COMIC BOOKS - READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/3/0126.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A26",
            "Lot Title": "DC Comics",
            "Lot Description": "Picture(s) part of description. The Brave and the Bold NO. 173",
            "Starting Bid": 4,
            "Quantity": 1,
            "Reserve": 4,
            "image": "/images/auctions/4/A26.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0127",
            "Lot Title": "COMIC BOOKS LOT OF 4",
            "Lot Description": "Picture(s) part of description. VINTAGE ARCHIE COMIC BOOKS - READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/3/0127.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A27",
            "Lot Title": "DC Comics",
            "Lot Description": "Picture(s) part of description. Super Powers NO. 3 Nov. '86",
            "Starting Bid": 4,
            "Quantity": 1,
            "Reserve": 4,
            "image": "/images/auctions/4/A27.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0128",
            "Lot Title": "COMIC BOOKS LOT OF 4",
            "Lot Description": "Picture(s) part of description. VINTAGE ARCHIE COMIC BOOKS - READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/3/0128.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A28",
            "Lot Title": "EC Entertainint Comic",
            "Lot Description": "Picture(s) part of description. EC The Vault of Horror No. 7 April",
            "Starting Bid": 4,
            "Quantity": 1,
            "Reserve": 4,
            "image": "/images/auctions/4/A28.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0129",
            "Lot Title": "COMIC BOOKS LOT OF 2",
            "Lot Description": "Picture(s) part of description. VINTAGE ARCHIE COMIC BOOKS - READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/3/0129.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A29",
            "Lot Title": "DC Comics",
            "Lot Description": "Picture(s) part of description. Tarzan Lord of the Jungle NO. 234 Jan. Reader Copy",
            "Starting Bid": 4,
            "Quantity": 1,
            "Reserve": 4,
            "image": "/images/auctions/4/A29.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0130",
            "Lot Title": "COMIC BOOKS LOT OF 4",
            "Lot Description": "Picture(s) part of description. VINTAGE COMIC BOOKS - READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0130.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A30",
            "Lot Title": "The New Warriors Comic Book",
            "Lot Description": "Picture(s) part of description. Marvel Comics April #22",
            "Starting Bid": 4,
            "Quantity": 1,
            "Reserve": 4,
            "image": "/images/auctions/4/A30.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0131",
            "Lot Title": "JANIS JOPLIN PEARL VINYL LP RECORD",
            "Lot Description": "Picture(s) part of description. JANIS JOPLIN FULL TILT BOOGIE 1971 COLUMBIA RECORDS PC30322",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0131.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A31",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A31.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0132",
            "Lot Title": "BILLY JOEL LOT OF 3 VINYL LP ALBUM",
            "Lot Description": "Picture(s) part of description. (1) AN INNOCENT MAN (2) THE STRANGER (3) GLASS HOUSES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0132.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A32",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A32.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0133",
            "Lot Title": "AIR SUPPLY LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) THE ONE THAT YOU LOVE (2) LOST IN LOVE ARISTA RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0133.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A33",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A33.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0134",
            "Lot Title": "REO SPEEDWAGON LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) NINE LIVES (2) WHEELS ARE TURNING. EPIC RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0134.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A34",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A34.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0135",
            "Lot Title": "TEN YEARS AFTER A SPACE IN TIME VINYL LP",
            "Lot Description": "Picture(s) part of description. COLUMBIA RECORDS 30801 1971 IN STEREO",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0135.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A35",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A35.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0136",
            "Lot Title": "STEELY DAN VINYL LP",
            "Lot Description": "Picture(s) part of description. 1977 ABC RECORDS AA0116",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0136.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A36",
            "Lot Title": "50 Cent Piece Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1960 Authentic Silver Coin",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 30,
            "image": "/images/auctions/4/A36.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0137",
            "Lot Title": "BOZ SCAGGS VINYL LP LOT OF 3",
            "Lot Description": "Picture(s) part of description. (1) SILK DEGREES (2) DOWN TWO THEN LEFT (3) SLOW DANCER",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0137.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A37",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1885 Silver Dollar Brilliant Uncirculated NGC",
            "Starting Bid": 25,
            "Quantity": 1,
            "Reserve": 100,
            "image": "/images/auctions/4/A37.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0138",
            "Lot Title": "HUEY LEWIS & THE NEWS VINYL LP",
            "Lot Description": "Picture(s) part of description. SPORTS. 1983 CHRYSALIS ECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0138.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A38",
            "Lot Title": "Gold Plated Dress Longines Quartz Watch",
            "Lot Description": "Picture(s) part of description. Men's Longines Crystal Gold Plated Watch",
            "Starting Bid": 25,
            "Quantity": 1,
            "Reserve": 75,
            "image": "/images/auctions/4/A38.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0139",
            "Lot Title": "PETER FRAMPTON LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) FRAMPTON COMES ALIVE (2) 1977 I AM IN YOU ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0139.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A39",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1971 Silver Dollar Brilliant Uncirculated 40% Silver",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 30,
            "image": "/images/auctions/4/A39.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0140",
            "Lot Title": "STONEGROUND LOG OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) HEARTS OF STONE 1978 WARNER BROS (2) FLAT OUT 1976 FLAT OUT RECORDS COPYRIGHT",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0140.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A40",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1971 Silver Dollar Brilliant Uncirculated 40% Silver",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 30,
            "image": "/images/auctions/4/A40.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0141",
            "Lot Title": "DIGITAL LASERDISC ",
            "Lot Description": "Picture(s) part of description. 1994 DELUXE THEATRICAL PRESENTATION DAS BOOT GERMAN WITH ENGLISH SUB TITLES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0141.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A41",
            "Lot Title": "LP Lot of 4",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 12,
            "image": "/images/auctions/4/A41.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0142",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. HARRISON FORD IN AIRFORCE ONE 1997 DELUXE WIDESCREEN PRESENTATOIN",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0142.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A42",
            "Lot Title": "LP Lot of 4",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 12,
            "image": "/images/auctions/4/A42.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0143",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. SCHWARZENEGGER IN TOTAL RECALL. 1990 DIGITAL STEREO SURROUND SOUND",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0143.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A43",
            "Lot Title": "LP Lot of 4",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 12,
            "image": "/images/auctions/4/A43.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0144",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. VAN DAMME IN SUDDEN DEATH. 1996 LETTERBOX MCA UNIVERSAL",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0144.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A44",
            "Lot Title": "LP Lot of 4",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 12,
            "image": "/images/auctions/4/A44.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0145",
            "Lot Title": "DIGITAL LASERDISC",
            "Lot Description": "Picture(s) part of description. VAN DAMME / DOLPH LUNDGREN IN UNIVERSAL SOLDIER. PARTIAL ORIGINAL SHRINK WRAP 1992",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0145.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A45",
            "Lot Title": "LP Lot of 4",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 12,
            "image": "/images/auctions/4/A45.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0146",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. SCALY THE LIZARD",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0146.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A46",
            "Lot Title": "Roll of 50 Indian Head Pennies",
            "Lot Description": "Picture(s) part of description. 1881 thru 1908 Indian Head Pennies",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A46.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0147",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. CHOCOLATE THE MOOSE",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0147.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A47",
            "Lot Title": "Indian Head Penny",
            "Lot Description": "Picture(s) part of description. 1895",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 2,
            "image": "/images/auctions/4/A47.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0148",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. STINGER THE SCORPION",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0148.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A48",
            "Lot Title": "Vintage Collectible Match Book",
            "Lot Description": "Picture(s) part of description. School of Hard Knocks Cut-N-Shoot",
            "Starting Bid": "Texas",
            "Quantity": 2,
            "Reserve": 1,
            "image": "/images/auctions/4/A48.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0149",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. LUCY THE GOOSE",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0149.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A49",
            "Lot Title": "Indian Head Penny",
            "Lot Description": "Picture(s) part of description. 1899",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 2,
            "image": "/images/auctions/4/A49.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0150",
            "Lot Title": "ORIGINAL TY BEANIE BABIES",
            "Lot Description": "Picture(s) part of description. RAINBOW THE CHAMELEON",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0150.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A50",
            "Lot Title": "Vintage Collectible Match Book",
            "Lot Description": "Picture(s) part of description. It's the Real Thing Coca Cola",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A50.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0151",
            "Lot Title": "GHOST HTF VHS",
            "Lot Description": "Picture(s) part of description. 1990 MCDONALD'S PROMO EDITION. RARE VHS TAPE HI-FI STEREO DOLBY SURROUND SOUND",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/3/0151.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A51",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A51.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0152",
            "Lot Title": "SCREAM RARE VHS TAPE",
            "Lot Description": "Picture(s) part of description. ORIGINAL SLIP COVER WESTCRAVEN. HARD TO FIND HORROR MOVIE",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/3/0152.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A52",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A52.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0153",
            "Lot Title": "CREATURE FROM THE HAUNTED SEA HTF VHS TAPE",
            "Lot Description": "Picture(s) part of description. HARD TO FIND VHS TAPE. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0153.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A53",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A53.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0154",
            "Lot Title": "SCARY MOVIE 2 VHS TAPE HTF",
            "Lot Description": "Picture(s) part of description. COMEDY HORROR FLICK WITH ORIGINAL SHRINK WRAP",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0154.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A54",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A54.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0155",
            "Lot Title": "MARS ATTACKS! VHS TAPE",
            "Lot Description": "Picture(s) part of description. WITH JACK NICHOLSON. HARD TO FIND SCI-FI COMEDY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0155.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A55",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A55.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0156",
            "Lot Title": "REBEL WILSON AUTOGRAPH COA",
            "Lot Description": "Picture(s) part of description. AUTOGRAPHED 2019 INSTYLE MAGAZINE",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0156.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A56",
            "Lot Title": "LaserDisc",
            "Lot Description": "Picture(s) part of description. Apollo 13 Laserdisc 1995",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A56.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0157",
            "Lot Title": "LOT OF 2 MARVEL COMICS",
            "Lot Description": "Picture(s) part of description. THE WEST COAST AVENGERS GIANT SIZED ANNUAL NO. 2 1987 AND WEST COAST AVENGERS VS. THE RANGERS 25TH ANNIVERSARY NO. 8",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0157.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A57",
            "Lot Title": "LaserDisc",
            "Lot Description": "Picture(s) part of description. Laserdisc - Widescreen Flirting with Disasster",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A57.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0158",
            "Lot Title": "MARVEL COMICS GROUP",
            "Lot Description": "Picture(s) part of description. TARZAN LORD OF THE JUNGLE NO. 4",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0158.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A58",
            "Lot Title": "LaserDisc",
            "Lot Description": "Picture(s) part of description. 1983 Star 80 Laserdisc Extended Play",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A58.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0159",
            "Lot Title": "MARVEL COMICS LOT OF 2 CLOAK & DAGGER",
            "Lot Description": "Picture(s) part of description. (1) GUEST STARRING SPIDER-MAN NO. 17 (2) GHOST RIDER & SPIDER-MAN JOIN CLOAK & DAGGER NO. 18",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0159.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A59",
            "Lot Title": "LaserDisc",
            "Lot Description": "Picture(s) part of description. Turner & Hooch Partial Original Shrink Wrap",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A59.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0160",
            "Lot Title": "LOT OF 4 MIXED COMIC BOOKS",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0160.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A60",
            "Lot Title": "LaserDisc",
            "Lot Description": "Picture(s) part of description. The Full Monty Widescreen Edition Laserdisc. Partial Original Shrink Wrap",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A60.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0161",
            "Lot Title": "CHICAGO LOT OF 2 VINYL LP ALBUMS",
            "Lot Description": "Picture(s) part of description. CHICAGO SIXTEEN 1982 WARNER BROS RECORDS & IF YOU LEAVE ME NOW 1983 COLUMBIA RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0161.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A61",
            "Lot Title": "The Mummy VHS Sealed",
            "Lot Description": "Picture(s) part of description. VHS Factory Sealed with Hersher's Hype Sticker",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A61.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0162",
            "Lot Title": "THE JIM CROCE COLLECTION VINYL LP RECORD",
            "Lot Description": "Picture(s) part of description. 1977 20 GREATEST HITS. TVLP-77024",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0162.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A62",
            "Lot Title": "Dragonheart Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A62.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0163",
            "Lot Title": "GORDON LIGHTFOOT VINYL LP ",
            "Lot Description": "Picture(s) part of description. GORD'S GOLD. 1975 WARNER BROS GATEFOLD ALBUM",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0163.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A63",
            "Lot Title": "The Rookie Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A63.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0164",
            "Lot Title": "EDDIE MONEY VINYL LP ",
            "Lot Description": "Picture(s) part of description. 1978 LIFE FOR THE TAKING. COLUMBIA RECORDS",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0164.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A64",
            "Lot Title": "The Natural Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A64.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0165",
            "Lot Title": "ERIC CLAPTON BACKLESS VINYL LP",
            "Lot Description": "Picture(s) part of description. 1978 RSO RECORDS RS-J-3039",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0165.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A65",
            "Lot Title": "Dr. Doolittle Sealed VHS Tape",
            "Lot Description": "Picture(s) part of description. Fox Video Watermark",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A65.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0166",
            "Lot Title": "CHUCK TAYLOR CONVERSE ALL-STAR ",
            "Lot Description": "Picture(s) part of description. HIGH TOP BASKETBALL SHOES SIZE 12 WHITE/RED/BLUE SPHICT ALLSTAR NEW/OLD STOCK NEVER WORN ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 300,
            "image": "/images/auctions/3/0166.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A66",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1901 Morgan Silver Dollar",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 40,
            "image": "/images/auctions/4/A66.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0167",
            "Lot Title": "G.H. BASS & CO. WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. SUNJUNS SHOES BLACK BRASS-LILY SIZE 7.5W",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/3/0167.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A67",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1878 (2nd Res.) Silver Dollar",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A67.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0168",
            "Lot Title": "BLACK DANSKO WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. SIZE 38 (8)",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/3/0168.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A68",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1904-0 PCGS MS64",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 100,
            "image": "/images/auctions/4/A68.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0169",
            "Lot Title": "BROWN DASKO DRESS WOMEN'S SHOES",
            "Lot Description": "Picture(s) part of description. SIZE 38 (8) ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0169.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A69",
            "Lot Title": "Half Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1908 Half Dollar",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/4/A69.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0170",
            "Lot Title": "STAR WARS TRILOGY VHS TAPES",
            "Lot Description": "Picture(s) part of description. 1995 TWENTIETH CENTURY FOX",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0170.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A70",
            "Lot Title": "Silver Dollar Authentic Coin",
            "Lot Description": "Picture(s) part of description. 1881-P Silver Dollar ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A70.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0171",
            "Lot Title": "TITANIC VHS TAPES",
            "Lot Description": "Picture(s) part of description. SET OF 2 1998 VHS HI-FI STEREO",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0171.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A71",
            "Lot Title": "Men At Work Two Hearts Vinyl LP & CD",
            "Lot Description": "Picture(s) part of description. Lot of 2 Vinyl LP Compact Disk (1) 1985 Columbia Records in Stero FC-40078 (2) Extremely Rare Long Box CD Unopened",
            "Starting Bid": 25,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A71.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0172",
            "Lot Title": "LORD OF THE RINGS VHS TAPES",
            "Lot Description": "Picture(s) part of description. RETURN OF THE KING. SET OF 2 ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0172.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A72",
            "Lot Title": "Elvis Presley Lot of 2 Vinyl LPs",
            "Lot Description": "Picture(s) part of description. (1) Rock 'n Roll 192 RCA LSP-10380 Victory (2) Unfinished Business Alternate Studio out takes",
            "Starting Bid": "Reel to Reel Record Co. #380. Both in original shrink wrap.",
            "Quantity": 5,
            "Reserve": 1,
            "image": "/images/auctions/4/A72.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0173",
            "Lot Title": "BRAVEHEART (MEL GIBSON) VHS TAPES",
            "Lot Description": "Picture(s) part of description. 1995 PARAMOUNT 2 VHS HI-FI STEREO TAPES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0173.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A73",
            "Lot Title": "Dirty Dancing 45 Vinyl LP",
            "Lot Description": "Picture(s) part of description. 1987 RCA Promo Not For Sale She's Like The Wind by Patrick Swayze",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A73.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0174",
            "Lot Title": "GONE WITH THE WIND VHS TAPES",
            "Lot Description": "Picture(s) part of description. 1939 DIGITAL VIDEO TRANSFER 2 VHS TAPES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0174.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A74",
            "Lot Title": "Survivor Eye of the Tiger Vinyl LP",
            "Lot Description": "Picture(s) part of description. 1982 CBS Scotti Bros. Records F2-38062 Stereo. Original Inner Sleeve",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A74.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0175",
            "Lot Title": "THE MOODY BLUES OUT OF THIS WORLD VINYL LP",
            "Lot Description": "Picture(s) part of description. LP MANUFACTURED IN FRANCE 1979 K-TELL INTL.",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0175.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A75",
            "Lot Title": "Styx Original LP VG",
            "Lot Description": "Picture(s) part of description. The Best of Times 45 LP",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A75.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0176",
            "Lot Title": "THE MOODY BLUES EVERY GOOD BOY DESERVES FAVOUR VINYL LP",
            "Lot Description": "Picture(s) part of description. 1971 DECCA RECORD CO LTD GATEFOLD WITH ORIGINAL INNER SLEEVE",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0176.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A76",
            "Lot Title": "Fringe Full Season DVD",
            "Lot Description": "Picture(s) part of description. The complete 1st season Sealed",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A76.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0177",
            "Lot Title": "THE MOODY BLUES TO OUR CHILDREN'S CHILDREN'S CHILDREN VINYL LP",
            "Lot Description": "Picture(s) part of description. 1969 THRESHHOLD MUSIC LTD",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0177.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A77",
            "Lot Title": "Kidnapped Full Season DVD",
            "Lot Description": "Picture(s) part of description. The complete series. Sealed 13 episodes on 3 discs.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A77.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0178",
            "Lot Title": "BAD COMPANY DESOLATION ANGELS VINYL LP",
            "Lot Description": "Picture(s) part of description. 1979 SWAN SONG INC. SS8506",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0178.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A78",
            "Lot Title": "Gem and the Holograms Full Season DVD",
            "Lot Description": "Picture(s) part of description. Season 1. Bonus feature video jukebox. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A78.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0179",
            "Lot Title": "THE MOODY BLUES LOT OF 4 VINYL LP",
            "Lot Description": "Picture(s) part of description. 4 ORIGINAL GATEFOLD VINYL LPs",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0179.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A79",
            "Lot Title": "Classic Slasher Collection DVD",
            "Lot Description": "Picture(s) part of description. 5 Blood soaked thrillers on 2 DVDs.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A79.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0180",
            "Lot Title": "NEIL DIAMOND LOT OF 4 VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) LIVE AT THE GREEK THEATRE (2) CLASSICS THE EARLY YEARS ORIGINAL HITS RECORDINGS (3) PRIMITIVE (4) GREATEST HITS BLPS-219-STEREO",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0180.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A80",
            "Lot Title": "Walker Texas Ranger Full Season DVD",
            "Lot Description": "Picture(s) part of description. The final season sealed.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/4/A80.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0181",
            "Lot Title": "FOREIGNER LOT OF 4 VINYL LP",
            "Lot Description": "Picture(s) part of description. ",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0181.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A81",
            "Lot Title": "The Little Mermaid Banned Copy VHS",
            "Lot Description": "Picture(s) part of description. Banned black diamond artwork. Very Rare.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A81.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0182",
            "Lot Title": "SWEET LEVEL HEADED VINYL LP",
            "Lot Description": "Picture(s) part of description. 1977 CAPITOL RECORDS SKAO-11744",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0182.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A82",
            "Lot Title": "Benjamin Orr Original Vinyl LP VG",
            "Lot Description": "Picture(s) part of description. Benjamin Orr the Lace 1986",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A82.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0183",
            "Lot Title": "LITTLE RIVER BAND LOT OF 2 VINYL LP MIXED EASY ROCK",
            "Lot Description": "Picture(s) part of description. LITTLE RIVER BANK TIME EXPOSURE & THE ELVIN BISHOP BANK - ROCK MY SOUL",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0183.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A83",
            "Lot Title": "The Rescuers & The Rescuers Down Under VHS",
            "Lot Description": "Picture(s) part of description. Walt Disney Black Diamond Classic VHS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A83.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0184",
            "Lot Title": "R & R RECORDS LOT OF 2 VINYL LP",
            "Lot Description": "Picture(s) part of description. JIM STEINMAN BAD FOR GOOD & POINT BLANK - THE HARD WAY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0184.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A84",
            "Lot Title": "Bambi VHS",
            "Lot Description": "Picture(s) part of description. Walt Disney Black Diamond Classic VHS",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A84.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0185",
            "Lot Title": "DENNIS THE MENACE COMIC BOOKS",
            "Lot Description": "Picture(s) part of description. LOT OF 9 READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0185.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A85",
            "Lot Title": "Bangles Different Light Original LP VG",
            "Lot Description": "Picture(s) part of description. 1985 CBS Inc. ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A85.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0186",
            "Lot Title": "DENNIS THE MENACE COMIC BOOKS",
            "Lot Description": "Picture(s) part of description. LOT OF 5 READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0186.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A86",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A86.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0187",
            "Lot Title": "DENNIS THE MENACE COMIC BOOKS",
            "Lot Description": "Picture(s) part of description. LOT OF 5 READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0187.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A87",
            "Lot Title": "Sealed DVDs",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A87.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0188",
            "Lot Title": "DENNIS THE MENACE COMIC BOOKS",
            "Lot Description": "Picture(s) part of description. LOT OF 5 READER COPIES",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/3/0188.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A88",
            "Lot Title": "Sausage Party Sealed DVD",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A88.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0189",
            "Lot Title": "CARDED HOT WHEELS LOT OF 4",
            "Lot Description": "Picture(s) part of description. TWO RED LINE SERIES & TWO REALISTIX. LOT OF 2 WITH 1 SHORT CARD",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0189.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A89",
            "Lot Title": "Peanuts 2-Movie Collection Sealed DVD",
            "Lot Description": "Picture(s) part of description.",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A89.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0190",
            "Lot Title": "CARDED 57 CHEVY LOT OF 4",
            "Lot Description": "Picture(s) part of description. ORIGINAL HOT WHEELS 57 CHEVY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0190.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A90",
            "Lot Title": "The Cat in the Hat Sealed DVD",
            "Lot Description": "Picture(s) part of description. Season 2 Volume 1 Sealed DVD",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A90.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0191",
            "Lot Title": "CARDED 57 CHEVY LOT OF 5",
            "Lot Description": "Picture(s) part of description. ORIGINAL HOT WHEELS 57 CHEVY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0191.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A91",
            "Lot Title": "Night At The Museum / Monkey Mischief DVD Set",
            "Lot Description": "Picture(s) part of description. Holiday Gift Set 2-DVD ",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A91.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0192",
            "Lot Title": "CARDED 57 CHEVY LOT OF 6",
            "Lot Description": "Picture(s) part of description. ORIGINAL HOT WHEELS 57 CHEVY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/3/0192.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A92",
            "Lot Title": "Caryl Hall John Oates / Oooh Yeah! Longbox CD",
            "Lot Description": "Picture(s) part of description. Longbox CD Extremely Rare",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A92.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0193",
            "Lot Title": "ORIGINAL CARDED HOT WHEELS ",
            "Lot Description": "Picture(s) part of description. 1982 OLD NO. 9 FIRE ENGINE UN-PUNCHED CARD",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0193.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A93",
            "Lot Title": "Roger Daltrey Can't Wait To See The Movie Longbox CD",
            "Lot Description": "Picture(s) part of description. Longbox CD Extremely Rare. Atlantic 1987",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A93.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0194",
            "Lot Title": "1991 HOT WHEELS BYWAYMAN",
            "Lot Description": "Picture(s) part of description. ORIGINAL 1991 CARDED",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0194.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A94",
            "Lot Title": "Russell Hitchcock Longbox CD",
            "Lot Description": "Picture(s) part of description. Longbox CD Very Rare. The Debut solo album from the lead singer of Air Supply",
            "Starting Bid": 10,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/4/A94.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0195",
            "Lot Title": "ORIGINAL HIRAKERS HOT WHEELS",
            "Lot Description": "Picture(s) part of description. UN-PUNCHED CARD 40'S WOODY 1979 MADE IN HONG KONG",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/3/0195.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A95",
            "Lot Title": "Personality Comics Led Zeppelin",
            "Lot Description": "Picture(s) part of description. Personality Comics Presents LED ZEPPELIN Featuring Jimmy Page. Unauthorized Biography Magazine",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/4/A95.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0196",
            "Lot Title": "MIXED LOT OF 2 MOTOWN VINYL LPS",
            "Lot Description": "Picture(s) part of description. (1) LIONEL RICHIE CAN'T SLOW DOWN (2) MARILYN MCCOO & BILLIE DAVIS JR. THE TWO OF US",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0196.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A96",
            "Lot Title": "Marvel Comics Special Collectors Item Issue No. 1",
            "Lot Description": "Picture(s) part of description. Rise of the Midnight Sons Nightstalkers NO. 1 Nov. Factory Sealed / Never Opened",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A96.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0197",
            "Lot Title": "MOTOWN - POINTER SISTERS LOT OF 2 VINYL LPS",
            "Lot Description": "Picture(s) part of description. CONTACT AND BREAKOUT",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0197.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A97",
            "Lot Title": "Marvel Comics Special Collectors Item Issue No. 1",
            "Lot Description": "Picture(s) part of description. Rise of the Midnight Sons Morbius No. 1 Sept. Factory Sealed / Never Opened",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A97.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0198",
            "Lot Title": "LOT OF 4 EASY LISTENING VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) ENGLAND DAN & JOHN FORD COLEY-SOME THINGS DON'T COME EASY (2) SEALS & CROFTS COLLECTION (3) BILLY VAUGHN PEARLY SHELLS (4) FIREFALL ELAN",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0198.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A98",
            "Lot Title": "Marvel Comics Lot of 2 Morbius",
            "Lot Description": "Picture(s) part of description. Morbius 001 Variant Edition / Morbius The LIving Vampire #2",
            "Starting Bid": 2,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/4/A98.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0199",
            "Lot Title": "LOT OF 4 EASY LISTENING VINYL LP",
            "Lot Description": "Picture(s) part of description. (1) JUSTIN HAYWARD - SONGWRITER (2) CORY HART - BOY IN THE BOX (3) KENNY G - SILHOUETTE (4) CHRIS REAR - WHATEVER HAPPENED TO BENNY SANTINY",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0199.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A99",
            "Lot Title": "3 Great Marvel Comics Factory Sealed",
            "Lot Description": "Picture(s) part of description. Marvel Comics Presents first Issue",
            "Starting Bid": "Howard The Duck No. 3",
            "Quantity": "Mystery Third Book",
            "Reserve": 5,
            "image": "/images/auctions/4/A99.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
          {
            "Lot Number": "0200",
            "Lot Title": "LAURA BRANIGAN LOT OF 2 VINYL LPS",
            "Lot Description": "Picture(s) part of description. (1) SELF-CONTROL & (2) BRANIGAN 2",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/3/0200.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/246641",
          },
          {
            "Lot Number": "A100",
            "Lot Title": "Rain of the Supermen Lot of 4 DC Comics",
            "Lot Description": "Picture(s) part of description. Superman in Action Comics with bonus poster enclosed",
            "Starting Bid": "No. 12 thru No. 15. Never Read",
            "Quantity": 5,
            "Reserve": 1,
            "image": "/images/auctions/4/A100.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/Vintage-and-modern-colletibles/event-catalog/247083",
          },
        ],
        onOpen: onOpen,
        open: openSection === 'auctions',
        keyname: 'auctions',
      }, // auctions
    ]
  }

  function onOpen(label) {
    if (openSection !== label) {
      setOpenSection(label)
    }
    else {
      setOpenSection('');
    }
  }

  return (
    <div>
      <Meta {...propList.meta} />
      <Hero {...propList.hero}/>
      {propList.AuctionSections.map((section, index) => {
        return (
          <AuctionCollapsible key={'section-'+index} {...section} />
        )
      })}
    </div>
  )
}
