import React, { useEffect, useState } from 'react'
import AuctionCollapsible from 'src/components/AuctionCollapsible'
import Hero from 'src/components/Hero'
import Meta from 'src/components/Meta'

export default function Home() {
  
  const [openSection, setOpenSection] = useState('auctions');

  let propList = {
    meta: {
      title: 'DJ\'s Auction House',
      description: 'DJ\'s Auction House is selling everything you could possibly need or want! Get in quick to see our latest items!',
      image: {
        src: '/images/favicon.png',
        alt: 'DJ\'s Auction House',
        width: 1024,
        height: 1024,
      },
    },
    hero: {
      title: `DJ's Auction House`,
      backgroundImage: '/images/hero/hero.jpg',
    },
    AuctionSections: [
      {
        title: 'Auctions',
        auctions: [
          {
            "Lot Number": "0500",
            "Lot Title": "Lebron James 33 Card Set Upper Deck",
            "Lot Description": "Picture part of description. All Rookie RC Cards",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 100,
            "image": "/images/auctions/12/0500.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0500",
          },
          {
            "Lot Number": "0501",
            "Lot Title": "Dell Sports Album with Yogi Berra Auto",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/12/0501.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0501",
          },
          {
            "Lot Number": "0502",
            "Lot Title": "1994 Cleveland Brown's Tribute Flyer",
            "Lot Description": "Picture part of description. Jim Brown signature Tribute Series #4",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0502.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0502",
          },
          {
            "Lot Number": "0503",
            "Lot Title": "Hard to Find Factory Sealed Batman Motion Picture Soundtrack",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/12/0503.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0503",
          },
          {
            "Lot Number": "0504",
            "Lot Title": "Genesis The Lamb Lies Down on Broadway LP Record",
            "Lot Description": "Picture part of description. 1974 Hard to Find Album SD-2-401",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 100,
            "image": "/images/auctions/12/0504.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0504",
          },
          {
            "Lot Number": "0505",
            "Lot Title": "Crosby",
            "Lot Description": " Stils",
            "Starting Bid": "Nash & Young Vinyl LP Deja Vu",
            "Quantity": "Picture part of description. Leather Like First Press 1970 Atlantic Gatefold Vinyl Record VG+Hype Sticker Audited and Certified by IRAA SD-7200",
            "Reserve": 3,
            "image": "/images/auctions/12/0505.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0505",
          },
          {
            "Lot Number": "0506",
            "Lot Title": "Marvel A-Team #1",
            "Lot Description": " #2 & #3",
            "Starting Bid": "Picture part of description. First Collector's Item Issue",
            "Quantity": 3,
            "Reserve": 1,
            "image": "/images/auctions/12/0506.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0506",
          },
          {
            "Lot Number": "0507",
            "Lot Title": "Original Sealed 2-count Value Pack Comic Books ",
            "Lot Description": "Picture part of description. one Free Bonus Super Hero Trading Card",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0507.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0507",
          },
          {
            "Lot Number": "0508",
            "Lot Title": "1885 Brilliant Uncirculated Silver Dollar",
            "Lot Description": "Picture part of description. NGC Graded",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 100,
            "image": "/images/auctions/12/0508.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0508",
          },
          {
            "Lot Number": "0509",
            "Lot Title": "1927 Silver Dollar San Francisco Mint",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 40,
            "image": "/images/auctions/12/0509.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0509",
          },
          {
            "Lot Number": "0510",
            "Lot Title": "1901 Morgan Silver Dollar",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 40,
            "image": "/images/auctions/12/0510.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0510",
          },
          {
            "Lot Number": "0511",
            "Lot Title": "Hot Wheels Hirakers '40s Woody #1131",
            "Lot Description": "Picture part of description. Unpunched 1979 Made in Hong Kong Card with Protector",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 35,
            "image": "/images/auctions/12/0511.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0511",
          },
          {
            "Lot Number": "0512",
            "Lot Title": "Hot Wheels RLC Jones Soda RV ",
            "Lot Description": "Picture part of description. Jones Soda Co Numbered 02596/05000",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/12/0512.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0512",
          },
          {
            "Lot Number": "0513",
            "Lot Title": "Fast and Furious Nissan Skyline GT-R Hot Wheels 2/8",
            "Lot Description": "Picture part of description. 2 Fast 2 Furious Paul Walker ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 15,
            "image": "/images/auctions/12/0513.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0513",
          },
          {
            "Lot Number": "0514",
            "Lot Title": "Hot Wheels Treasure Hunt #6",
            "Lot Description": "Picture part of description. '34 Ford Comes in Protective Clam",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0514.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0514",
          },
          {
            "Lot Number": "0515",
            "Lot Title": "Carded Hot Wheels Bywayman #220",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0515.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0515",
          },
          {
            "Lot Number": "0516",
            "Lot Title": "Rare Bubba Ho-Tep DVD",
            "Lot Description": "Picture part of description. Hard to find",
            "Starting Bid": "Limited Edition Sealed Horror Film",
            "Quantity": 3,
            "Reserve": 1,
            "image": "/images/auctions/12/0516.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0516",
          },
          {
            "Lot Number": "0517",
            "Lot Title": "Neck Deep Wishful Thinkin",
            "Lot Description": "Picture part of description. Viny LP",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0517.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0517",
          },
          {
            "Lot Number": "0518",
            "Lot Title": "Bob Dylan Slow Train Coming Viny Record",
            "Lot Description": "Picture part of description. 1979 Original Vinyl",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0518.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0518",
          },
          {
            "Lot Number": "0519",
            "Lot Title": "Saturday Night Live Vinyl LP",
            "Lot Description": "Picture part of description. 1976 Arista Records",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0519.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0519",
          },
          {
            "Lot Number": "0520",
            "Lot Title": "Carly Simon Come Upstairs Vinyl",
            "Lot Description": "Picture part of description. 1980 Warner Bros Records",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0520.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0520",
          },
          {
            "Lot Number": "0521",
            "Lot Title": "Factory Shrink Wrapped Fat Albert Music CD",
            "Lot Description": "Picture part of description. HEY HEY HEY It's Fat Alberts Party CD 2005",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0521.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0521",
          },
          {
            "Lot Number": "0522",
            "Lot Title": "Rare Grease DVD with Leather Jacket",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/12/0522.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0522",
          },
          {
            "Lot Number": "0523",
            "Lot Title": "2018 Marvel Comic Shop News #1",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0523.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0523",
          },
          {
            "Lot Number": "0524",
            "Lot Title": "Signed 8 x 10 Captain Marvel Movie Poster COA",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 20,
            "image": "/images/auctions/12/0524.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0524",
          },
          {
            "Lot Number": "0525",
            "Lot Title": "Signed Photo of Jim McMahon 8 x 10",
            "Lot Description": "Picture part of description. Handing off to Walter Payton",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0525.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0525",
          },
          {
            "Lot Number": "0526",
            "Lot Title": "Original Matt Groening Sketch with COA Bart Simpson",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0526.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0526",
          },
          {
            "Lot Number": "0527",
            "Lot Title": "2 VHS Lot The Little Mermaid",
            "Lot Description": "Picture part of description. (1) Banned Black Diamond Copy (2) Masterpiece Special Edition",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 45,
            "image": "/images/auctions/12/0527.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0527",
          },
          {
            "Lot Number": "0528",
            "Lot Title": "Ben Hur Deluxe Letterbox Edition VHS",
            "Lot Description": "Picture part of description. 35th Anniversary Edition VHS Factory Sealed",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0528.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0528",
          },
          {
            "Lot Number": "0529",
            "Lot Title": "Factory Sealed The Wizard of Oz Clamshell VHS",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0529.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0529",
          },
          {
            "Lot Number": "0530",
            "Lot Title": "Original Sealed 8-Track Cartridge Eagles Their Greatest Hits 71 thru 75",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0530.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0530",
          },
          {
            "Lot Number": "0531",
            "Lot Title": "Original Sealed 8-Track Cartridge Jefferson Starship Spitfire",
            "Lot Description": "Picture part of description. 1976 Grunt Records",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0531.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0531",
          },
          {
            "Lot Number": "0532",
            "Lot Title": "Original Sealed 8-Track Cartridge Seals & Crofts Greatest Hits",
            "Lot Description": "Picture part of description. 1976",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0532.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0532",
          },
          {
            "Lot Number": "0533",
            "Lot Title": "Original Factored Sealed 8-Track Cartridge The Mamas & The Papas",
            "Lot Description": "Picture part of description. 1971 16 of their greatest hits",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0533.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0533",
          },
          {
            "Lot Number": "0534",
            "Lot Title": "Original Sealed 8-Track Cartridge",
            "Lot Description": "Picture part of description. Rock and Roll Gold Various Artists 1976",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0534.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0534",
          },
          {
            "Lot Number": "0535",
            "Lot Title": "Blood Sweat & Tears Vinyl Record",
            "Lot Description": "Picture part of description. LP Album Stereo/Mono CS-9720",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0535.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0535",
          },
          {
            "Lot Number": "0536",
            "Lot Title": "Grand Funk Closer to Home Vinyl Record",
            "Lot Description": "Picture part of description. LP",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0536.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0536",
          },
          {
            "Lot Number": "0537",
            "Lot Title": "1978 Journey Infinitive Album",
            "Lot Description": "Picture part of description. Record",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0537.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0537",
          },
          {
            "Lot Number": "0538",
            "Lot Title": "Billy joel's Greatest Hits Vol. 1 & 2",
            "Lot Description": "Picture part of description. 2 Record Gateway Album with front cover damage and back cover stain",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0538.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0538",
          },
          {
            "Lot Number": "0539",
            "Lot Title": "Huey Lewis & the News Vinyl Record",
            "Lot Description": "Picture part of description. 1983 Sports Album",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0539.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0539",
          },
          {
            "Lot Number": "0540",
            "Lot Title": "Super Rare Factory Sealed Long Box PRETENDERS CD",
            "Lot Description": "Picture part of description. 1990 Compact Disc Packed!",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0540.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0540",
          },
          {
            "Lot Number": "0541",
            "Lot Title": "1988 Rare Factory Sealed Longbox CD ",
            "Lot Description": "Picture part of description. Russell Hitchcock Debut solo from the lead singer of Air Supply",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0541.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0541",
          },
          {
            "Lot Number": "0542",
            "Lot Title": "Daryl Hall & John Oats Compact Disc ",
            "Lot Description": "Picture part of description. Rare Factory Sealed Longbox Edition Oh Yeah",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0542.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0542",
          },
          {
            "Lot Number": "0543",
            "Lot Title": "Rare Factory Sealed Long Box Ric Ocasek CD",
            "Lot Description": "Picture part of description. 1986 Compact Disc This Side of Paradise",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0543.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0543",
          },
          {
            "Lot Number": "0544",
            "Lot Title": "Rare Factory Sealed Longbox Warren Zevon CD",
            "Lot Description": "Picture part of description. 1989 Virgin Records CD",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0544.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0544",
          },
          {
            "Lot Number": "0545",
            "Lot Title": "Gold Key Bugs Bunny 12 Cent Edition Comic Book",
            "Lot Description": "Picture part of description. Reader Copy",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0545.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0545",
          },
          {
            "Lot Number": "0546",
            "Lot Title": "Run Baby Run The True Story of Nicky Cruz Comic Book",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0546.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0546",
          },
          {
            "Lot Number": "0547",
            "Lot Title": "DC Supergirl #21",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0547.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0547",
          },
          {
            "Lot Number": "0548",
            "Lot Title": "DC Future State Catwoman Issue #1",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0548.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0548",
          },
          {
            "Lot Number": "0549",
            "Lot Title": "Marvel Comic KARNAK #001",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0549.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0549",
          },
          {
            "Lot Number": "0550",
            "Lot Title": "The Doors LaserDisc",
            "Lot Description": "Picture part of description. Double disc Set. Widescreen Edition. Starring Val Kilmer & Meg Ryan",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0550.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0550",
          },
          {
            "Lot Number": "0551",
            "Lot Title": "Aliens 1995 Widescreen Edition",
            "Lot Description": "Picture part of description. THX Laser-Disc",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0551.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0551",
          },
          {
            "Lot Number": "0552",
            "Lot Title": "Laser Video Disc Special Edition Close Encounters of the Third Kind",
            "Lot Description": "Picture part of description. 1980 LaserVision",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0552.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0552",
          },
          {
            "Lot Number": "0553",
            "Lot Title": "Air Force One Laser Disc",
            "Lot Description": "Picture part of description. Deluxe Widescreen Presentation 1997 Harrison Ford",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0553.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0553",
          },
          {
            "Lot Number": "0554",
            "Lot Title": "Laser Video Disc Major League",
            "Lot Description": "Picture part of description. 1989 Extended Play",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0554.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0554",
          },
          {
            "Lot Number": "0555",
            "Lot Title": "The Legendary Babe Ruth Commerative Plate",
            "Lot Description": "Picture part of description. The Hamilton Collection Plate #1422 D Made in USA",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/12/0555.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0555",
          },
          {
            "Lot Number": "0556",
            "Lot Title": "Darryl Strawberry Limited Edition Commerative Plate",
            "Lot Description": "Picture part of description. Plate #582",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/12/0556.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0556",
          },
          {
            "Lot Number": "0557",
            "Lot Title": "Mark Maguire Rookie Card RC",
            "Lot Description": "Picture part of description. 1987 Donruss Rated Rookie",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0557.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0557",
          },
          {
            "Lot Number": "0558",
            "Lot Title": "Colbe Bryant ShowStopper",
            "Lot Description": "Picture part of description. 1997-98 TOPPS Finest with Coating CSG Graded 9",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0558.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0558",
          },
          {
            "Lot Number": "0559",
            "Lot Title": "Lebron James Rookie Card RC",
            "Lot Description": "Picture part of description. 2003-04 Upper Deck #19 Graded Gem-MT",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 25,
            "image": "/images/auctions/12/0559.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0559",
          },
          {
            "Lot Number": "0560",
            "Lot Title": "Longines Gold-Plated Quartz Watch",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0560.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0560",
          },
          {
            "Lot Number": "0561",
            "Lot Title": "1881-P Silver Dollar",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 75,
            "image": "/images/auctions/12/0561.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0561",
          },
          {
            "Lot Number": "0562",
            "Lot Title": "1896-P Silver Dollar",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 75,
            "image": "/images/auctions/12/0562.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0562",
          },
          {
            "Lot Number": "0563",
            "Lot Title": "1908 Silver Coin",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 30,
            "image": "/images/auctions/12/0563.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0563",
          },
          {
            "Lot Number": "0564",
            "Lot Title": "1878 Silver Dollar",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 50,
            "image": "/images/auctions/12/0564.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0564",
          },
          {
            "Lot Number": "0565",
            "Lot Title": "Blonde Call Me 45 LP",
            "Lot Description": "Picture part of description. Vinyl Record 1980",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0565.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0565",
          },
          {
            "Lot Number": "0566",
            "Lot Title": "Dire Straits 45 LPs Money for Nothing",
            "Lot Description": "Picture part of description. 1985 Vinyl Record",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0566.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0566",
          },
          {
            "Lot Number": "0567",
            "Lot Title": "45 LPs Asia Heat Of The Moment",
            "Lot Description": "Picture part of description. 1982",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0567.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0567",
          },
          {
            "Lot Number": "0568",
            "Lot Title": "45 LPs Heart These Dreams Cover",
            "Lot Description": "Picture part of description. Shell Shock 1985",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0568.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0568",
          },
          {
            "Lot Number": "0569",
            "Lot Title": "Betty Boop Coca Cola Brand Salt & Pepper Set",
            "Lot Description": "Picture part of description. Domed Lunch Box Salt & Pepper Set Betty Boop",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0569.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0569",
          },
          {
            "Lot Number": "0570",
            "Lot Title": "Betty Boop Valentines Doll",
            "Lot Description": "Picture part of description. Sugar Loaf with tags",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0570.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0570",
          },
          {
            "Lot Number": "0571",
            "Lot Title": "Hot Wheels Lot of 4 ",
            "Lot Description": "Picture part of description. 4Sealed Die Cast Cars",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0571.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0571",
          },
          {
            "Lot Number": "0572",
            "Lot Title": "Hot Wheels Lot of 4 ",
            "Lot Description": "Picture part of description. 4Sealed Die Cast Cars",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0572.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0572",
          },
          {
            "Lot Number": "0573",
            "Lot Title": "Hot Wheels Lot of 4 ",
            "Lot Description": "Picture part of description. 4Sealed Die Cast Cars",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0573.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0573",
          },
          {
            "Lot Number": "0574",
            "Lot Title": "Hot Wheels Lot of 4 ",
            "Lot Description": "Picture part of description. 4Sealed Die Cast Cars",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0574.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0574",
          },
          {
            "Lot Number": "0575",
            "Lot Title": "PineCar Dry Transfer Decals",
            "Lot Description": "Picture part of description. Never Opened",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0575.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0575",
          },
          {
            "Lot Number": "0576",
            "Lot Title": "Rare Longbox CD Titanic Factory Sealed",
            "Lot Description": "Picture part of description. Music From the Motion Picture Titanic",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/12/0576.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0576",
          },
          {
            "Lot Number": "0577",
            "Lot Title": "Rare Factory Sealed DVD Longbox Chocolat",
            "Lot Description": "Picture part of description. Collector's Series",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/12/0577.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0577",
          },
          {
            "Lot Number": "0578",
            "Lot Title": "Rare Factory Sealed Longbox Nottinghill",
            "Lot Description": "Picture part of description. 1999 Collectors Editon Julia Roberts & Hugh Grant",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/12/0578.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0578",
          },
          {
            "Lot Number": "0579",
            "Lot Title": "Rare DVD LongBox Dr",
            "Lot Description": "Doolittle 2",
            "Starting Bid": "Picture part of description. Factory Shrink Wrapped with open top",
            "Quantity": 5,
            "Reserve": 1,
            "image": "/images/auctions/12/0579.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0579",
          },
          {
            "Lot Number": "0580",
            "Lot Title": "Rare DVD LongBox Spy Kids",
            "Lot Description": "Picture part of description. Factory Shrink Wrapped with open top",
            "Starting Bid": 5,
            "Quantity": 1,
            "Reserve": 5,
            "image": "/images/auctions/12/0580.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0580",
          },
          {
            "Lot Number": "0581",
            "Lot Title": "INXS KICK LP Record",
            "Lot Description": "Picture part of description. 1987 Atlantic 81796-1",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 8,
            "image": "/images/auctions/12/0581.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0581",
          },
          {
            "Lot Number": "0582",
            "Lot Title": "Lot of 2 Records Urban Cowboy & Urban Chipmunk",
            "Lot Description": "Picture part of description. Original Motion Picture Soundtrack. Urbank Chipmunk Promotional Not For Sale Album",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/12/0582.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0582",
          },
          {
            "Lot Number": "0583",
            "Lot Title": "ZZ Top Lot of 2 Vinyl Records ",
            "Lot Description": "Picture part of description. ZZ Top Eliminator & The Best of ZZ Top",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/12/0583.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0583",
          },
          {
            "Lot Number": "0584",
            "Lot Title": "2 Album Lot Linda Ronstadt Greatest Hits",
            "Lot Description": "Picture part of description. Vol. 1 & 2",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 10,
            "image": "/images/auctions/12/0584.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0584",
          },
          {
            "Lot Number": "0585",
            "Lot Title": "1997 Original Motion Picture Soundtrack Close Encounters of the Third Kind",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0585.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0585",
          },
          {
            "Lot Number": "0586",
            "Lot Title": "Lot of 2 Avengers Standoff",
            "Lot Description": "Picture part of description. Marvel Standoff Assault on Pleasant Hill Alpha 001 & Omega 001",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0586.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0586",
          },
          {
            "Lot Number": "0587",
            "Lot Title": "Marvel Masterpieces #1 Issue",
            "Lot Description": "Picture part of description. Marvel Comics News Stand Edition",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0587.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0587",
          },
          {
            "Lot Number": "0588",
            "Lot Title": "Spider-Man Classics #1",
            "Lot Description": "Picture part of description. 1993 Marvel Comics 1st Smash Issue. News Stand Edition",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0588.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0588",
          },
          {
            "Lot Number": "0589",
            "Lot Title": "Lot of 4 Superman in Action Comics",
            "Lot Description": "Picture part of description. 1993 unread copies",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0589.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0589",
          },
          {
            "Lot Number": "0590",
            "Lot Title": "Original Ty Beanie Babies Chocolate the Moose",
            "Lot Description": "Picture part of description. 1993 with/without errors",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0590.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0590",
          },
          {
            "Lot Number": "0591",
            "Lot Title": "Original Ty Beanie Babies Stinger the Scorpion",
            "Lot Description": "Picture part of description. 1998 with / without error label",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0591.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0591",
          },
          {
            "Lot Number": "0592",
            "Lot Title": "Original Ty Beanie Baby Rainbow the Iguana",
            "Lot Description": "Picture part of description. 1997 with rare colors",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0592.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0592",
          },
          {
            "Lot Number": "0593",
            "Lot Title": "Original Ty Beanie Babies Scaly the Lizard",
            "Lot Description": "Picture part of description. 1999 with Halogram Label",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0593.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0593",
          },
          {
            "Lot Number": "0594",
            "Lot Title": "Original Ty Beanie Babies Loosy the Goose",
            "Lot Description": "Picture part of description. 1998 with / without error tag",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0594.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0594",
          },
          {
            "Lot Number": "0595",
            "Lot Title": "Total Recall Laser Disc",
            "Lot Description": "Picture part of description. 1990 Extended Play Arnold Schwarznegger",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0595.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0595",
          },
          {
            "Lot Number": "0596",
            "Lot Title": "Wizard of Oz Laser Video Disc",
            "Lot Description": "Picture part of description. 50th Anniversary Extended Play Reclamation of the 1939 Movie",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0596.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0596",
          },
          {
            "Lot Number": "0597",
            "Lot Title": "Deluxe Letter Box Edition LaserDisc West Side Story ",
            "Lot Description": "Picture part of description. Extended Play 2-Disc Set 1989",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0597.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0597",
          },
          {
            "Lot Number": "0598",
            "Lot Title": "Factory Sealed ACDC DVD",
            "Lot Description": "Picture part of description. No bull The Director's Cut 2008",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0598.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0598",
          },
          {
            "Lot Number": "0599",
            "Lot Title": "Rare CD Longbox Lee Greenwood",
            "Lot Description": "Picture part of description. 1992 American Patriot Factory Sealed",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0599.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100#lot-image-0599",
          },
          {
            "Lot Number": "0600",
            "Lot Title": "Ultra Rare Card Marvel.com/milk",
            "Lot Description": "Picture part of description. ",
            "Starting Bid": 3,
            "Quantity": 1,
            "Reserve": 3,
            "image": "/images/auctions/12/0600.jpg",
            "href": "https://www.proxibid.com/DJ-Auctions-LLC/HIGH-END-ESTATE-FINDS-AUCTION/event-catalog/251163?ipp=100&p=2#lot-image-0600",
          },
        ],
        onOpen: onOpen,
        open: openSection === 'auctions',
        keyname: 'auctions',
      }, // auctions
    ]
  }

  function onOpen(label) {
    if (openSection !== label) {
      setOpenSection(label)
    }
    else {
      setOpenSection('');
    }
  }

  return (
    <div>
      <Meta {...propList.meta} />
      <Hero {...propList.hero}/>
      {propList.AuctionSections.map((section, index) => {
        return (
          <AuctionCollapsible key={'section-'+index} {...section} />
        )
      })}
    </div>
  )
}
